#! /bin/sh

[ "a`echo c | sed s/c/b/ 2>/dev/null`" = "ab" ] || { echo >&2 "'sed' is required, but not installed."; exit 1; }
# Determine which flag sed uses for extended regular expressions.
# -E is POSIX. -r is for GNU sed older than 4.2.
echo a | sed -E s/a/b/ >/dev/null 2>&1 && SED_ERE=-E || SED_ERE=-r

case $OSTYPE in
	darwin*)
	LIBTOOLIZE=glibtoolize
	;;
	*)
	LIBTOOLIZE=libtoolize
	;;
esac

PACKAGE_VERSION=`sed "$SED_ERE" 's/#define PACKAGE_VERSION "(.+)"/\1/' libfaad/version.h`
sed -i.bak "$SED_ERE" "s/^(AC_INIT.+)[0-9]+\.[0-9]+\.[0-9]+(.+)$/\1$PACKAGE_VERSION\2/" configure.ac

aclocal -I .                   && \
autoheader                     && \
$LIBTOOLIZE --automake && \
automake --add-missing && \
autoconf                       && \
echo "Ready to run ./configure"
