#!/bin/bash

echo ""
echo "----running setup for xmms-aac plugin----"
echo "don't forget to install libfaad before !!"
echo "check http://www.audiocoding.com"
echo ""

aclocal -I .
libtoolize --automake
automake --add-missing
autoconf
echo "******"
echo "ready to run ./configure (check '--help' for options)"
echo "******"
